import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import favicon from "../public/favicon.png";
import ScrollToTop from "@/components/common/ScrollToTop";

// Body font (matches the reference site)
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

// Title font (matches the reference site)
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "iBEST BHUTAN",
  description: "Generated by create next app",
  icons: {
    icon: favicon.src,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${inter.variable} h-full scroll-smooth antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
